version: "3.9"

services:
    postgres:
        image: ankane/pgvector:v0.4.1
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ama
            POSTGRES_PASSWORD: ama_pass
            POSTGRES_DB: ama_db

volumes:
    postgres-data:
